
[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
[font]
size = 16.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16

# Custom Key Bindings -- MacOS specific

# Reference: https://medium.com/@jogarcia/alacritty-with-tmux-escape-sequence-for-custom-binding-47df5e401c51

######################## tmux key bindings #######################

# open new tmux window
[[keyboard.bindings]]
chars = "\uE000"
key = "T"
mods = "Command"

# open new tmux window with fzf
[[keyboard.bindings]]
chars = "\uE013"
key = "T"
mods = "Command|Shift"

# close tmux window/pane
[[keyboard.bindings]]
chars = "\uE001"
key = "W"
mods = "Command"

# detach tmux session
[[keyboard.bindings]]
chars = "\uE014"
key = "M"
mods = "Command|Shift"

# split tmux window horizontally
[[keyboard.bindings]]
chars = "\uE002"
key = "H"
mods = "Command|Shift"

# split tmux window vertically
[[keyboard.bindings]]
chars = "\uE003"
key = "V"
mods = "Command|Shift"

# switch to next window
[[keyboard.bindings]]
chars = "\uE113"
key = "Right"
mods = "Command|Alt"

# switch to previous window
[[keyboard.bindings]]
chars = "\uE114"
key = "Left"
mods = "Command|Alt"

# select tmux windows by window number
[[keyboard.bindings]]
chars = "\uE004"
key = "1"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE005"
key = "2"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE006"
key = "3"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE007"
key = "4"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE008"
key = "5"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE009"
key = "6"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE010"
key = "7"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE011"
key = "8"
mods = "Command"

[[keyboard.bindings]]
chars = "\uE012"
key = "9"
mods = "Command"

# resize vertical split pane
[[keyboard.bindings]]
chars = "\uE022"
key = "Up"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\uE023"
key = "Down"
mods = "Command|Control"

# resize horizontal split pane
[[keyboard.bindings]]
chars = "\uE024"
key = "Left"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\uE025"
key = "Right"
mods = "Command|Control"

######################## Vim key bindings #######################

# switch focus between buffers 
[[keyboard.bindings]]
chars = "\uE015"
key = "E"
mods = "Command|Shift"

# toggle nerdtree (file explorer)
[[keyboard.bindings]]
chars = "\uE016"
key = "B"
mods = "Command"

# fuzzy find files
[[keyboard.bindings]]
chars = "\uE017"
key = "P"
mods = "Command"

# live grep from files
[[keyboard.bindings]]
chars = "\uE018"
key = "F"
mods = "Command|Shift"

# text search
[[keyboard.bindings]]
chars = "\uE019"
key = "F"
mods = "Command"

# commend a line
[[keyboard.bindings]]
chars = "\uE026"
key = "/"
mods = "Command"

# open copilot chat
[[keyboard.bindings]]
chars = "\uE027"
key = "I"
mods = "Command|Shift"

[general]
live_config_reload = true

